# Generated by Django 2.1.3 on 2018-11-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='searchResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
    ]
