# Generated by Django 2.1.3 on 2018-11-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresults',
            name='search_key',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
