# Generated by Django 2.1.3 on 2018-11-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_search', '0002_searchresults_search_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_key', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='searchResults',
        ),
    ]
