# Generated by Django 2.1.3 on 2018-11-17 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quick_search', '0003_auto_20181117_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
