# Generated by Django 2.1.3 on 2018-11-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quick_search', '0004_searchresult_time_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchresult',
            old_name='search_key',
            new_name='query',
        ),
    ]
