# Generated by Django 2.1.3 on 2018-11-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_search', '0005_auto_20181117_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='heading',
            field=models.CharField(default='No header available', max_length=200),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='text',
            field=models.CharField(default='No body available', max_length=2000),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='url',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
